name: py36class
channels:
  - plotly
  - anaconda
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _anaconda_depends=2019.03=py36_0
  - _libgcc_mutex=0.1=main
  - alabaster=0.7.12=py36_0
  - anaconda=custom=py36_1
  - anaconda-client=1.7.2=py36_0
  - anaconda-project=0.8.4=py_0
  - aplus=0.11.0=py_1
  - argh=0.26.2=py36_0
  - arrow-cpp=0.16.0=py36hb0edad2_0
  - arviz=0.7.0=py_0
  - asn1crypto=1.3.0=py36_0
  - astroid=2.3.3=py36_0
  - astropy=4.0=py36h7b6447c_0
  - atomicwrites=1.3.0=py36_1
  - attrs=19.3.0=py_0
  - autopep8=1.4.4=py_0
  - aws-sdk-cpp=1.7.164=h1f8afcc_0
  - babel=2.8.0=py_0
  - backcall=0.1.0=py36_0
  - backports=1.0=py_2
  - backports.os=0.1.1=py36_0
  - backports.shutil_get_terminal_size=1.0.0=py36_2
  - beautifulsoup4=4.8.2=py36_0
  - binutils_impl_linux-64=2.33.1=he1b5a44_7
  - binutils_linux-64=2.33.1=h9595d00_17
  - bitarray=1.2.1=py36h7b6447c_0
  - bkcharts=0.2=py36_0
  - blas=1.0=mkl
  - bleach=3.1.0=py36_0
  - blosc=1.17.1=he1b5a44_0
  - bokeh=2.0.0=py36_0
  - boost-cpp=1.70.0=ha2d47e9_1
  - boto=2.49.0=py36_0
  - boto3=1.9.191=py_0
  - botocore=1.12.191=py_0
  - bottleneck=1.3.2=py36heb32a55_0
  - bqplot=0.12.6=pyh8c360ce_0
  - branca=0.3.1=py_0
  - brotli=1.0.7=he1b5a44_1001
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.15.0=h516909a_1001
  - ca-certificates=2019.11.28=hecc5488_0
  - cachetools=3.1.1=py_0
  - cairo=1.16.0=h18b612c_1001
  - catalogue=1.0.0=py_0
  - certifi=2019.11.28=py36h9f0ad1d_1
  - cffi=1.14.0=py36h2e261b9_0
  - cftime=1.1.1.2=py36h785e9b2_0
  - chardet=3.0.4=py36_1003
  - cld2-cffi=0.1.4=py36he1b5a44_1000
  - click=7.1.1=py_0
  - cloudpickle=1.3.0=py_0
  - clyent=1.2.2=py36_1
  - colorama=0.4.3=py_0
  - contextlib2=0.6.0.post1=py_0
  - convertdate=2.1.3=py_1000
  - cpuonly=1.0=0
  - cryptography=2.8=py36h1ba5d50_0
  - curl=7.69.1=hbc83047_0
  - cycler=0.10.0=py36_0
  - cymem=2.0.3=py36h831f99a_1
  - cython=0.29.15=py36he6710b0_0
  - cython-blis=0.4.1=py36h516909a_0
  - cytoolz=0.10.1=py36h7b6447c_0
  - dask=1.1.4=py36_1
  - dask-core=1.1.4=py36_1
  - dbus=1.13.12=h746ee38_0
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - diff-match-patch=20181111=py_0
  - dill=0.3.1.1=py36h9f0ad1d_1
  - distributed=1.28.1=py36_0
  - docutils=0.16=py36_0
  - entrypoints=0.3=py36_0
  - ephem=3.7.7.1=py36h516909a_0
  - et_xmlfile=1.0.1=py36_0
  - expat=2.2.6=he6710b0_0
  - fastcache=1.1.0=py36h7b6447c_0
  - fastparquet=0.3.3=py36hc1659b7_0
  - fbprophet=0.6=py36he1b5a44_0
  - ffmpeg=4.1.3=h167e202_0
  - flake8=3.7.9=py36_0
  - flask=1.1.1=py_1
  - fontconfig=2.13.1=he4413a7_1000
  - freetype=2.9.1=h8a8886c_1
  - freetype-py=2.1.0.post1=py_0
  - fribidi=1.0.5=h7b6447c_0
  - ftfy=4.4.2=py36_0
  - future=0.18.2=py36_0
  - gcc_impl_linux-64=7.3.0=habb00fd_1
  - gcc_linux-64=7.3.0=h553295d_17
  - get_terminal_size=1.0.0=haa9412d_0
  - gettext=0.19.8.1=hc5be6a0_1002
  - gevent=1.4.0=py36h7b6447c_0
  - gflags=2.2.2=he1b5a44_1002
  - giflib=5.2.1=h516909a_2
  - glib=2.63.1=h5a9c865_0
  - glog=0.4.0=he1b5a44_1
  - gmp=6.1.2=h6c8ec71_1
  - gmpy2=2.0.8=py36h10f8cd9_2
  - gnutls=3.6.5=hd3a4fd2_1002
  - graphite2=1.3.13=h23475e2_0
  - graphviz=2.42.3=h0511662_0
  - greenlet=0.4.15=py36h7b6447c_0
  - grpc-cpp=1.25.0=h213be95_2
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - gxx_impl_linux-64=7.3.0=hdf63c60_1
  - gxx_linux-64=7.3.0=h553295d_17
  - h5py=2.10.0=py36h7918eee_0
  - harfbuzz=2.4.0=h37c48d4_1
  - hdf4=4.2.13=hf30be14_1003
  - hdf5=1.10.4=hb1b8bf9_0
  - heapdict=1.0.1=py_0
  - holidays=0.10.1=py_0
  - html5lib=1.0.1=py36_0
  - hypothesis=5.5.4=py_0
  - icu=58.2=h9c2bf20_1
  - idna=2.9=py_1
  - ijson=2.6.1=py_0
  - imageio=2.8.0=py_0
  - imagesize=1.2.0=py_0
  - importlib_metadata=1.5.0=py36_0
  - inflection=0.3.1=py_1
  - intel-openmp=2020.0=166
  - intervaltree=3.0.2=py_0
  - ipydatawidgets=4.0.1=py_0
  - ipykernel=5.1.4=py36h39e3cac_0
  - ipyleaflet=0.12.3=py_1
  - ipympl=0.5.6=pyh8c360ce_0
  - ipyscales=0.4.0=py_1
  - ipython=7.13.0=py36h5ca1d4c_0
  - ipython_genutils=0.2.0=py36_0
  - ipyvolume=0.5.2=py36_0
  - ipyvue=1.2.1=pyh9f0ad1d_0
  - ipyvuetify=1.2.1=pyh8c360ce_0
  - ipywebrtc=0.5.0=py36_0
  - ipywidgets=7.5.1=py_0
  - isort=4.3.21=py36_0
  - itsdangerous=1.1.0=py36_0
  - jasper=1.900.1=h07fcdf6_1006
  - jbig=2.1=hdba287a_0
  - jdcal=1.4.1=py_0
  - jedi=0.15.2=py36_0
  - jeepney=0.4.3=py_0
  - jinja2=2.11.1=py_0
  - jmespath=0.9.5=py_0
  - joblib=0.14.1=py_0
  - jpeg=9c=h14c3975_1001
  - json5=0.9.3=py_0
  - jsonschema=3.2.0=py36_0
  - jupyter=1.0.0=py36_7
  - jupyter_client=6.1.0=py_0
  - jupyter_console=6.1.0=py_0
  - jupyter_contrib_core=0.3.3=py_2
  - jupyter_contrib_nbextensions=0.5.1=py36_0
  - jupyter_core=4.6.1=py36_0
  - jupyter_highlight_selected_word=0.2.0=py36_1000
  - jupyter_latex_envs=1.4.6=py36_1000
  - jupyter_nbextensions_configurator=0.4.1=py36_0
  - jupyterlab=2.0.1=py_0
  - jupyterlab_server=1.0.7=py_0
  - keyring=21.1.0=py36_0
  - kiwisolver=1.1.0=py36he6710b0_0
  - koalas=0.22.0=py_0
  - krb5=1.17.1=h173b8e3_0
  - lame=3.100=h14c3975_1001
  - lazy-object-proxy=1.4.3=py36h7b6447c_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libblas=3.8.0=15_mkl
  - libcblas=3.8.0=15_mkl
  - libcurl=7.69.1=h20c2e04_0
  - libedit=3.1.20181209=hc058e9b_0
  - libevent=2.1.10=h72c5cf5_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libiconv=1.15=h516909a_1006
  - liblapack=3.8.0=15_mkl
  - liblapacke=3.8.0=15_mkl
  - libnetcdf=4.6.2=hbdf4f91_1001
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.11.0=h8b12597_0
  - libsodium=1.0.16=h1bed415_0
  - libspatialindex=1.9.3=he6710b0_0
  - libssh2=1.9.0=h1ba5d50_1
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=hc3755c2_3
  - libtool=2.4.6=h7b6447c_5
  - libuuid=2.32.1=h14c3975_1000
  - libwebp=1.0.2=h56121f0_5
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.9=hea5a465_1
  - libxslt=1.1.33=h7d1a2b0_0
  - llvmlite=0.31.0=py36hd408876_0
  - locket=0.2.0=py36_1
  - lunarcalendar=0.0.9=py_0
  - lxml=4.5.0=py36hefd8a0e_0
  - lz4-c=1.8.3=he1b5a44_1001
  - lzo=2.10=h49e0be7_2
  - markupsafe=1.1.1=py36h7b6447c_0
  - matplotlib=3.1.3=py36_0
  - matplotlib-base=3.1.3=py36hef1b27d_0
  - mccabe=0.6.1=py36_1
  - mistune=0.8.4=py36h7b6447c_0
  - mkl=2020.0=166
  - mkl-service=2.3.0=py36he904b0f_0
  - mkl_fft=1.0.15=py36ha843d7b_0
  - mkl_random=1.1.0=py36hd6b4f25_0
  - mock=4.0.1=py_0
  - more-itertools=8.2.0=py_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.1=hdf1c602_3
  - mpmath=1.1.0=py36_0
  - multipledispatch=0.6.0=py36_0
  - multiprocess=0.70.9=py36h8c4c3a4_1
  - murmurhash=1.0.0=py36he1b5a44_0
  - nbconvert=5.6.1=py36_0
  - nbformat=5.0.4=py_0
  - ncurses=6.2=he6710b0_0
  - netcdf4=1.5.1.2=py36had58050_0
  - nettle=3.4.1=h1bed415_1002
  - networkx=2.4=py_0
  - ninja=1.9.0=py36hfd86e86_0
  - nltk=3.4.5=py36_0
  - nodejs=12.4.0=he1b5a44_0
  - nose=1.3.7=py36_2
  - notebook=6.0.3=py36_0
  - numba=0.48.0=py36h0573a6f_0
  - numexpr=2.7.1=py36h423224d_0
  - numpy=1.18.1=py36h4f9e942_0
  - numpy-base=1.18.1=py36hde5b4d6_1
  - numpydoc=0.9.2=py_0
  - olefile=0.46=py36_0
  - opencv=4.1.0=py36h5517eff_4
  - openh264=1.8.0=hdbcaa40_1000
  - openpyxl=3.0.3=py_0
  - openssl=1.1.1e=h516909a_0
  - packaging=20.3=py_0
  - pandas=0.24.2=py36he6710b0_0
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py36_1
  - pango=1.42.4=ha030887_1
  - parquet-cpp=1.5.1=2
  - parso=0.5.2=py_0
  - partd=1.1.0=py_0
  - path=13.1.0=py36_0
  - path.py=12.4.0=0
  - pathlib2=2.3.5=py36_0
  - pathos=0.2.5=py_0
  - pathtools=0.1.2=py_1
  - patsy=0.5.1=py36_0
  - pcre=8.43=he6710b0_0
  - pep8=1.7.1=py36_0
  - pexpect=4.8.0=py36_0
  - pickleshare=0.7.5=py36_0
  - pillow=7.0.0=py36hb39fc2d_0
  - pip=20.0.2=py36_1
  - pixman=0.38.0=h7b6447c_0
  - plac=0.9.6=py_1
  - plotly-orca=1.3.1=1
  - pluggy=0.13.1=py36_0
  - ply=3.11=py36_0
  - pox=0.2.7=py_0
  - ppft=1.6.6.1=py36h9f0ad1d_1
  - preshed=3.0.2=py36h831f99a_2
  - progressbar2=3.50.0=py_2
  - prometheus_client=0.7.1=py_0
  - prompt-toolkit=3.0.4=py_0
  - prompt_toolkit=3.0.4=0
  - psutil=5.7.0=py36h7b6447c_0
  - ptyprocess=0.6.0=py36_0
  - py=1.8.1=py_0
  - py4j=0.10.7=py_1
  - pyarrow=0.16.0=py36h8b68381_1
  - pycodestyle=2.5.0=py36_0
  - pycosat=0.6.3=py36h7b6447c_0
  - pycparser=2.20=py_0
  - pycrypto=2.6.1=py36h14c3975_9
  - pycurl=7.43.0.5=py36h1ba5d50_0
  - pydocstyle=4.0.1=py_0
  - pyemd=0.5.1=py36hb3f55d8_1000
  - pyflakes=2.1.1=py36_0
  - pygments=2.6.1=py_0
  - pylint=2.4.4=py36_0
  - pyodbc=4.0.30=py36he6710b0_0
  - pyopenssl=19.1.0=py36_0
  - pyparsing=2.4.6=py_0
  - pyphen=0.9.5=py_0
  - pyqt=5.9.2=py36h05f1152_2
  - pyrsistent=0.15.7=py36h7b6447c_0
  - pysocks=1.7.1=py36_0
  - pyspark=2.4.5=py_0
  - pystan=2.19.1.1=py36hb3f55d8_1
  - pytables=3.6.1=py36h71ec239_0
  - pytest=5.4.1=py36_0
  - pytest-arraydiff=0.3=py36h39e3cac_0
  - pytest-astropy=0.8.0=py_0
  - pytest-astropy-header=0.1.2=py_0
  - pytest-doctestplus=0.5.0=py_0
  - pytest-openfiles=0.4.0=py_0
  - pytest-remotedata=0.3.2=py36_0
  - python=3.6.10=hcf32534_1
  - python-blosc=1.8.1=py36hf484d3e_0
  - python-dateutil=2.8.1=py_0
  - python-graphviz=0.13.2=py_0
  - python-jsonrpc-server=0.3.4=py_0
  - python-language-server=0.31.9=py36_0
  - python-levenshtein=0.12.0=py36h516909a_1001
  - python-snappy=0.5.4=py36hee44bf9_1
  - python-utils=2.4.0=py_0
  - python_abi=3.6=1_cp36m
  - pythreejs=2.2.0=pyh8c360ce_0
  - pytorch=1.4.0=py3.6_cpu_0
  - pytz=2019.3=py_0
  - pywavelets=1.1.1=py36h7b6447c_0
  - pyxdg=0.26=py_0
  - pyyaml=5.3.1=py36h7b6447c_0
  - pyzmq=18.1.1=py36he6710b0_0
  - qdarkstyle=2.8=py_0
  - qt=5.9.7=h5867ecd_1
  - qtawesome=0.7.0=py_0
  - qtconsole=4.7.2=py_0
  - qtpy=1.9.0=py_0
  - quandl=3.4.6=py36_0
  - re2=2020.03.03=he1b5a44_0
  - readline=8.0=h7b6447c_0
  - redis-py=3.3.7=py_0
  - requests=2.23.0=py36_0
  - rope=0.16.0=py_0
  - rtree=0.9.3=py36_0
  - ruamel_yaml=0.15.87=py36h7b6447c_0
  - s3fs=0.2.2=py_0
  - s3transfer=0.2.1=py36_0
  - scikit-image=0.16.2=py36h0573a6f_0
  - scikit-learn=0.22.1=py36hd81dba3_0
  - scipy=1.4.1=py36h0b6359f_0
  - seaborn=0.10.0=py_0
  - secretstorage=3.1.2=py36_0
  - send2trash=1.5.0=py36_0
  - setuptools=46.1.1=py36_0
  - setuptools-git=1.2=py_1
  - simplegeneric=0.8.1=py36_2
  - singledispatch=3.4.0.3=py36_0
  - sip=4.19.8=py36hf484d3e_0
  - six=1.14.0=py36_0
  - snappy=1.1.8=he1b5a44_1
  - snowballstemmer=2.0.0=py_0
  - sortedcollections=1.1.2=py36_0
  - sortedcontainers=2.1.0=py36_0
  - soupsieve=2.0=py_0
  - spacy=2.2.3=py36hc9558a2_0
  - sphinx=2.4.4=py_0
  - sphinxcontrib=1.0=py36_1
  - sphinxcontrib-applehelp=1.0.2=py_0
  - sphinxcontrib-devhelp=1.0.2=py_0
  - sphinxcontrib-htmlhelp=1.0.3=py_0
  - sphinxcontrib-jsmath=1.0.1=py_0
  - sphinxcontrib-qthelp=1.0.3=py_0
  - sphinxcontrib-serializinghtml=1.1.4=py_0
  - sphinxcontrib-websupport=1.2.1=py_0
  - spyder=4.1.1=py36_1
  - spyder-kernels=1.9.0=py36_0
  - sqlalchemy=1.3.15=py36h7b6447c_1
  - sqlite=3.31.1=h7b6447c_0
  - srsly=1.0.0=py36he1b5a44_0
  - statsmodels=0.11.0=py36h7b6447c_0
  - sympy=1.5.1=py36_0
  - tabulate=0.8.7=pyh9f0ad1d_0
  - tbb=2020.0=hfd86e86_0
  - tblib=1.6.0=py_0
  - terminado=0.8.3=py36_0
  - testpath=0.4.4=py_0
  - textacy=0.6.2=py36_0
  - textblob=0.15.3=py_0
  - thinc=7.3.0=py36hc9558a2_0
  - thrift=0.11.0=py36he1b5a44_1001
  - thrift-cpp=0.12.0=hf3afdfd_1004
  - tk=8.6.8=hbc83047_0
  - toolz=0.10.0=py_0
  - torchvision=0.5.0=py36_cpu
  - tornado=6.0.4=py36h7b6447c_1
  - tqdm=4.43.0=py_0
  - traitlets=4.3.3=py36_0
  - traittypes=0.2.1=py_1
  - typed-ast=1.4.1=py36h7b6447c_0
  - typing_extensions=3.7.4.1=py36_0
  - ujson=1.35=py36h14c3975_0
  - unicodecsv=0.14.1=py36_0
  - unidecode=1.1.1=py_0
  - unixodbc=2.3.7=h14c3975_0
  - urllib3=1.25.8=py36_0
  - vaex-arrow=0.4.2=py_0
  - vaex-astro=0.6.1=py_1
  - vaex-core=1.5.0=py36hb3f55d8_0
  - vaex-distributed=0.3.0=py_0
  - vaex-hdf5=0.5.6=py_0
  - vaex-jupyter=0.4.1=py_0
  - vaex-server=0.2.1=py_0
  - vaex-viz=0.3.8=py_1
  - vispy=0.6.4=py36hf5ce8a7_0
  - wasabi=0.6.0=py_0
  - watchdog=0.10.2=py36_0
  - wcwidth=0.1.8=py_0
  - webencodings=0.5.1=py36_1
  - werkzeug=1.0.0=py_0
  - wheel=0.34.2=py36_0
  - widgetsnbextension=3.5.1=py36_0
  - wordcloud=1.6.0=py36h516909a_0
  - wrapt=1.12.1=py36h7b6447c_1
  - wurlitzer=2.0.0=py36_0
  - x264=1!152.20180806=h14c3975_0
  - xarray=0.14.1=py_1
  - xlrd=1.2.0=py36_0
  - xlsxwriter=1.2.8=py_0
  - xlwt=1.3.0=py36_0
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.9=h516909a_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxpm=3.5.13=h516909a_0
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-libxt=1.1.5=h516909a_1003
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.2.4=h14c3975_4
  - yaml=0.1.7=had09818_2
  - yapf=0.28.0=py_0
  - zeromq=4.3.1=he6710b0_3
  - zict=2.0.0=py_0
  - zipp=2.2.0=py_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.4=h3b9ef0a_2
  - pip:
    - absl-py==0.9.0
    - alpha-vantage==2.1.3
    - amqp==2.5.2
    - arctic==1.79.2
    - astor==0.8.1
    - billiard==3.6.3.0
    - celery==4.4.0
    - chart-studio==1.0.0
    - chartpy==0.1.4
    - cmdstanpy==0.4.0
    - colorlover==0.3.0
    - configparser==5.0.0
    - cssselect==1.1.0
    - cufflinks==0.17.0
    - cvlib==0.2.4
    - dash==1.9.0
    - dash-core-components==1.8.0
    - dash-html-components==1.0.2
    - dash-renderer==1.2.4
    - dash-table==4.6.0
    - distro==1.4.0
    - enum-compat==0.0.3
    - feedfinder2==0.0.4
    - feedparser==5.2.1
    - filelock==3.0.12
    - findatapy==0.1.7
    - finmarketpy==0.11.3
    - flask-compress==1.4.0
    - flatbuffers==1.12
    - funcsigs==1.0.2
    - fxcmpy==1.2.6
    - gast==0.2.2
    - gensim==3.8.1
    - google-api-core==1.16.0
    - google-auth==1.12.0
    - google-auth-oauthlib==0.4.1
    - google-cloud-core==1.3.0
    - google-cloud-storage==1.26.0
    - google-pasta==0.2.0
    - google-resumable-media==0.5.0
    - googleapis-common-protos==1.51.0
    - grpcio==1.27.2
    - imutils==0.5.3
    - jieba3k==0.35.1
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.0
    - kombu==4.6.8
    - lz4==3.0.2
    - markdown==3.2.1
    - mockextras==1.0.2
    - modin==0.5.4
    - msgpack-python==0.5.6
    - multiprocessing-on-dill==3.5.0a4
    - multitasking==0.0.9
    - newspaper3k==0.2.8
    - oauthlib==3.1.0
    - opt-einsum==3.2.0
    - pandas-datareader==0.8.1
    - pdfkit==0.6.1
    - pdfminer-six==20200124
    - plotly==4.5.4
    - plotly-express==0.4.1
    - progressbar==2.5
    - protobuf==3.11.3
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycryptodome==3.9.7
    - pymongo==3.10.1
    - pytesseract==0.3.3
    - ray==0.7.1
    - regex==2020.2.20
    - requests-file==1.4.3
    - requests-oauthlib==1.3.0
    - retrying==1.3.3
    - rise==5.6.1
    - rsa==4.0
    - sacremoses==0.0.38
    - seasonal==0.3.1
    - sentencepiece==0.1.85
    - sklearn==0.0
    - smart-open==1.10.0
    - socketio-client==0.7.2
    - tabula-py==1.4.3
    - tensorboard==2.1.1
    - tensorflow==2.1.0
    - tensorflow-estimator==2.1.0
    - termcolor==1.1.0
    - tinysegmenter==0.3
    - tldextract==2.2.2
    - tokenizers==0.5.2
    - transformers==2.6.0
    - twython==3.7.0
    - typing==3.7.4.1
    - tzlocal==2.0.0
    - vadersentiment==3.3.1
    - vine==1.3.0
    - websocket-client==0.57.0
    - yfinance==0.1.54

