name: py36class
channels:
  - plotly
  - anaconda
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _anaconda_depends=2019.03=py36_0
  - alabaster=0.7.12=py36_0
  - anaconda=custom=py36_1
  - anaconda-client=1.7.2=py36_0
  - anaconda-project=0.8.4=py_0
  - arviz=0.5.1=py_1
  - asn1crypto=1.2.0=py36_0
  - astroid=2.3.3=py36_0
  - astropy=3.2.3=py36he774522_0
  - atomicwrites=1.3.0=py36_1
  - attrs=19.3.0=py_0
  - babel=2.7.0=py_0
  - backcall=0.1.0=py36_0
  - backports=1.0=py_2
  - backports.os=0.1.1=py36_0
  - backports.shutil_get_terminal_size=1.0.0=py36_2
  - beautifulsoup4=4.8.1=py36_0
  - bitarray=1.1.0=py36he774522_0
  - bkcharts=0.2=py36h7e685f7_0
  - blas=1.0=mkl
  - bleach=3.1.0=py36_0
  - blosc=1.16.3=h7bd577a_0
  - bokeh=1.4.0=py36_0
  - boto=2.49.0=py36_0
  - bottleneck=1.3.1=py36h8c2d366_0
  - bzip2=1.0.8=he774522_0
  - ca-certificates=2019.11.28=hecc5488_0
  - catalogue=0.0.8=py_0
  - certifi=2019.11.28=py36_0
  - cffi=1.13.2=py36h7a1dbc1_0
  - cftime=1.0.4.2=py36hc8d92b1_0
  - chardet=3.0.4=py36_1003
  - click=7.0=py36_0
  - cloudpickle=1.2.2=py_0
  - clyent=1.2.2=py36_1
  - colorama=0.4.1=py36_0
  - comtypes=1.1.7=py36_0
  - console_shortcut=0.1.1=3
  - contextlib2=0.6.0.post1=py_0
  - convertdate=2.1.3=py_1000
  - cpuonly=1.0=0
  - cryptography=2.8=py36h7a1dbc1_0
  - curl=7.67.0=h2a8f88b_0
  - cycler=0.10.0=py36h009560c_0
  - cymem=2.0.3=py36h6538335_0
  - cython=0.29.14=py36ha925a31_0
  - cython-blis=0.4.1=py36hfa6e2cd_0
  - cytoolz=0.10.1=py36he774522_0
  - dask=2.8.1=py_0
  - dask-core=2.8.1=py_0
  - decorator=4.4.1=py_0
  - defusedxml=0.6.0=py_0
  - dill=0.3.1.1=py36_0
  - distributed=2.8.1=py_0
  - docutils=0.15.2=py36_0
  - entrypoints=0.3=py36_0
  - ephem=3.7.7.0=py36hfa6e2cd_0
  - et_xmlfile=1.0.1=py36h3d2d736_0
  - fastcache=1.1.0=py36he774522_0
  - fastparquet=0.3.2=py36hc8d92b1_0
  - fbprophet=0.5=py36h6538335_0
  - flask=1.1.1=py_0
  - freetype=2.9.1=ha9979f8_1
  - fsspec=0.6.0=py_0
  - get_terminal_size=1.0.0=h38e98db_0
  - gevent=1.4.0=py36he774522_0
  - graphviz=2.38.0=h6538335_1011
  - greenlet=0.4.15=py36hfa6e2cd_0
  - h5py=2.9.0=py36h5e291fa_0
  - hdf4=4.2.13=h712560f_2
  - hdf5=1.10.4=h7ebc959_0
  - heapdict=1.0.1=py_0
  - holidays=0.9.11=py_0
  - html5lib=1.0.1=py36_0
  - icc_rt=2019.0.0=h0cc432a_1
  - icu=58.2=ha66f8fd_1
  - idna=2.8=py36_0
  - imageio=2.6.1=py36_0
  - imagesize=1.1.0=py36_0
  - importlib_metadata=0.23=py36_0
  - inflection=0.3.1=py_1
  - intel-openmp=2019.4=245
  - ipykernel=5.1.3=py36h39e3cac_0
  - ipython=7.9.0=py36h39e3cac_0
  - ipython_genutils=0.2.0=py36h3c5d0ee_0
  - ipywidgets=7.5.1=py_0
  - isort=4.3.21=py36_0
  - itsdangerous=1.1.0=py36_0
  - jdcal=1.4.1=py_0
  - jedi=0.15.1=py36_0
  - jinja2=2.10.3=py_0
  - joblib=0.14.0=py_0
  - jpeg=9b=hb83a4c4_2
  - json5=0.8.5=py_0
  - jsonschema=3.2.0=py36_0
  - jupyter=1.0.0=py36_7
  - jupyter_client=5.3.4=py36_0
  - jupyter_console=5.2.0=py36_1
  - jupyter_contrib_core=0.3.3=py_2
  - jupyter_contrib_nbextensions=0.5.1=py36_0
  - jupyter_core=4.6.1=py36_0
  - jupyter_highlight_selected_word=0.2.0=py36_1000
  - jupyter_latex_envs=1.4.4=py36_1000
  - jupyter_nbextensions_configurator=0.4.1=py36_0
  - jupyterlab=1.2.3=py_0
  - jupyterlab_server=1.0.6=py_0
  - keyring=19.2.0=py36_0
  - kiwisolver=1.1.0=py36ha925a31_0
  - krb5=1.16.1=hc04afaa_7
  - lazy-object-proxy=1.4.3=py36he774522_0
  - libcurl=7.67.0=h2a8f88b_0
  - libiconv=1.15=h1df5818_7
  - libnetcdf=4.6.1=h411e497_2
  - libpng=1.6.37=h2a8f88b_0
  - libpython=2.0=py36_0
  - libsodium=1.0.16=h9d3ae62_0
  - libssh2=1.8.2=h7a1dbc1_0
  - libtiff=4.1.0=h56a325e_0
  - libxml2=2.9.9=h464c3ec_0
  - libxslt=1.1.33=h579f668_0
  - llvmlite=0.30.0=py36ha925a31_0
  - locket=0.2.0=py36hfed976d_1
  - lunardate=0.2.0=py_0
  - lxml=4.4.1=py36h1350720_0
  - lz4-c=1.8.1.2=h2fa13f4_0
  - lzo=2.10=h6df0209_2
  - m2w64-binutils=2.25.1=5
  - m2w64-bzip2=1.0.6=6
  - m2w64-crt-git=5.0.0.4636.2595836=2
  - m2w64-gcc=5.3.0=6
  - m2w64-gcc-ada=5.3.0=6
  - m2w64-gcc-fortran=5.3.0=6
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gcc-objc=5.3.0=6
  - m2w64-gmp=6.1.0=2
  - m2w64-headers-git=5.0.0.4636.c0ad18a=2
  - m2w64-isl=0.16.1=2
  - m2w64-libiconv=1.14=6
  - m2w64-libmangle-git=5.0.0.4509.2e5a9a2=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - m2w64-make=4.1.2351.a80a8b8=2
  - m2w64-mpc=1.0.3=3
  - m2w64-mpfr=3.1.4=4
  - m2w64-pkg-config=0.29.1=2
  - m2w64-toolchain=5.3.0=7
  - m2w64-toolchain_win-64=2.4.0=0
  - m2w64-tools-git=5.0.0.4592.90b8472=2
  - m2w64-windows-default-manifest=6.4=3
  - m2w64-winpthreads-git=5.0.0.4634.697f757=2
  - m2w64-zlib=1.2.8=10
  - markupsafe=1.1.1=py36he774522_0
  - matplotlib=3.1.1=py36hc8f65d3_0
  - matplotlib-base=3.1.2=py36h2981e6d_1
  - mccabe=0.6.1=py36_1
  - menuinst=1.4.16=py36he774522_0
  - mistune=0.8.4=py36he774522_0
  - mkl=2019.4=245
  - mkl-service=2.3.0=py36hb782905_0
  - mkl_fft=1.0.15=py36h14836fe_0
  - mkl_random=1.1.0=py36h675688f_0
  - mock=3.0.5=py36_0
  - more-itertools=7.2.0=py36_0
  - mpmath=1.1.0=py36_0
  - msgpack-python=0.6.1=py36h74a9793_1
  - msys2-conda-epoch=20160418=1
  - multipledispatch=0.6.0=py36_0
  - multiprocess=0.70.9=py36hfa6e2cd_0
  - murmurhash=1.0.0=py36h6538335_0
  - nbconvert=5.6.1=py36_0
  - nbformat=4.4.0=py36h3a5bc1b_0
  - netcdf4=1.4.2=py36h812ae01_0
  - networkx=2.4=py_0
  - ninja=1.9.0=py36h74a9793_0
  - nltk=3.4.5=py36_0
  - nose=1.3.7=py36_2
  - notebook=6.0.2=py36_0
  - numba=0.46.0=py36hf9181ef_0
  - numexpr=2.7.0=py36hdce8814_0
  - numpy=1.17.4=py36h4320e6b_0
  - numpy-base=1.17.4=py36hc3f5095_0
  - numpydoc=0.9.1=py_0
  - olefile=0.46=py36_0
  - openpyxl=3.0.1=py_0
  - openssl=1.1.1d=he774522_3
  - packaging=19.2=py_0
  - pandas=0.24.2
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py36_1
  - parso=0.5.1=py_0
  - partd=1.1.0=py_0
  - path.py=12.0.2=py_0
  - pathlib2=2.3.5=py36_0
  - pathos=0.2.5=py_0
  - patsy=0.5.1=py36_0
  - pep8=1.7.1=py36_0
  - pickleshare=0.7.5=py36_0
  - pillow=6.2.1=py36hdc69c19_0
  - pip=19.3.1=py36_0
  - plac=0.9.6=py_1
  - plotly-orca=1.2.1=1
  - pluggy=0.13.1=py36_0
  - ply=3.11=py36_0
  - powershell_shortcut=0.0.1=2
  - pox=0.2.7=py_0
  - ppft=1.6.6.1=py36_0
  - preshed=3.0.2=py36h6538335_1
  - prometheus_client=0.7.1=py_0
  - psutil=5.6.5=py36he774522_0
  - py=1.8.0=py36_0
  - pycodestyle=2.5.0=py36_0
  - pycosat=0.6.3=py36hfa6e2cd_0
  - pycparser=2.19=py36_0
  - pycrypto=2.6.1=py36hfa6e2cd_9
  - pycurl=7.43.0.3=py36h7a1dbc1_0
  - pyflakes=2.1.1=py36_0
  - pygments=2.4.2=py_0
  - pylint=2.4.4=py36_0
  - pyodbc=4.0.27=py36ha925a31_0
  - pyopenssl=19.1.0=py36_0
  - pyparsing=2.4.5=py_0
  - pyqt=5.9.2=py36h6538335_2
  - pyreadline=2.1=py36_1
  - pyrsistent=0.15.6=py36he774522_0
  - pysocks=1.7.1=py36_0
  - pystan=2.19.1.1=py36h12199cf_1
  - pytables=3.6.1=py36h1da0976_0
  - pytest=5.3.0=py36_0
  - pytest-arraydiff=0.3=py36h39e3cac_0
  - pytest-astropy=0.6.0=py_0
  - pytest-astropy-header=0.1.1=py_0
  - pytest-doctestplus=0.5.0=py_0
  - pytest-openfiles=0.4.0=py_0
  - pytest-remotedata=0.3.2=py36_0
  - python=3.6.9=h5500b2f_0
  - python-blosc=1.8.1=py36h6538335_0
  - python-graphviz=0.13.2=py_0
  - python-snappy=0.5.4=py36hd25c944_1
  - pytorch=1.3.1=py3.6_cpu_0
  - pytz=2019.3=py_0
  - pywavelets=1.1.1=py36he774522_0
  - pywin32=223=py36hfa6e2cd_1
  - pywin32-ctypes=0.2.0=py36_0
  - pywinpty=0.5.5=py36_1000
  - pyyaml=5.1.2=py36he774522_0
  - pyzmq=18.1.0=py36ha925a31_0
  - qt=5.9.7=vc14h73c81de_0
  - qtawesome=0.6.0=py_0
  - qtconsole=4.6.0=py_0
  - qtpy=1.9.0=py_0
  - quandl=3.4.6=py36_0
  - redis-py=3.3.7=py_0
  - requests=2.22.0=py36_0
  - rise=5.6.0=py36_0
  - rope=0.14.0=py_0
  - ruamel_yaml=0.15.46=py36hfa6e2cd_0
  - scikit-image=0.15.0=py36ha925a31_0
  - scikit-learn=0.21.3=py36h6288b17_0
  - scipy=1.3.1=py36h29ff71c_0
  - seaborn=0.9.0=pyh91ea838_1
  - send2trash=1.5.0=py36_0
  - setuptools=42.0.1=py36_0
  - simplegeneric=0.8.1=py36_2
  - singledispatch=3.4.0.3=py36h17d0c80_0
  - sip=4.19.8=py36h6538335_0
  - six=1.13.0=py36_0
  - snappy=1.1.7=h777316e_3
  - snowballstemmer=2.0.0=py_0
  - sortedcollections=1.1.2=py36_0
  - sortedcontainers=2.1.0=py36_0
  - soupsieve=1.9.5=py36_0
  - spacy=2.2.3=py36he980bc4_0
  - sphinx=2.2.1=py_0
  - sphinxcontrib=1.0=py36_1
  - sphinxcontrib-applehelp=1.0.1=py_0
  - sphinxcontrib-devhelp=1.0.1=py_0
  - sphinxcontrib-htmlhelp=1.0.2=py_0
  - sphinxcontrib-jsmath=1.0.1=py_0
  - sphinxcontrib-qthelp=1.0.2=py_0
  - sphinxcontrib-serializinghtml=1.1.3=py_0
  - sphinxcontrib-websupport=1.1.2=py_0
  - spyder=3.3.6=py36_0
  - spyder-kernels=0.5.2=py36_0
  - sqlalchemy=1.3.11=py36he774522_0
  - sqlite=3.30.1=he774522_0
  - srsly=0.2.0=py36h6538335_0
  - statsmodels=0.10.1=py36h8c2d366_0
  - sympy=1.4=py36_0
  - tbb=2019.4=h74a9793_0
  - tblib=1.5.0=py_0
  - terminado=0.8.3=py36_0
  - testpath=0.4.4=py_0
  - textblob=0.15.3=py_0
  - thinc=7.3.0=py36he980bc4_0
  - thrift=0.11.0=py36h6538335_1001
  - tk=8.6.8=hfa6e2cd_0
  - toolz=0.10.0=py_0
  - torchvision=0.4.2=py36_cpu
  - tornado=6.0.3=py36he774522_0
  - tqdm=4.40.0=py_0
  - traitlets=4.3.3=py36_0
  - typed-ast=1.4.0=py36he774522_0
  - unicodecsv=0.14.1=py36h6450c06_0
  - urllib3=1.24.2=py36_0
  - vc=14.1=h0510ff6_4
  - vs2015_runtime=14.16.27012=hf0eaf9b_0
  - wasabi=0.4.0=py_0
  - wcwidth=0.1.7=py36h3d5aa90_0
  - webencodings=0.5.1=py36_1
  - werkzeug=0.16.0=py_0
  - wheel=0.33.6=py36_0
  - widgetsnbextension=3.5.1=py36_0
  - win_inet_pton=1.1.0=py36_0
  - win_unicode_console=0.5=py36hcdbd4b5_0
  - wincertstore=0.2=py36h7fe50ca_0
  - winpty=0.4.3=4
  - wordcloud=1.6.0=py36hfa6e2cd_0
  - wrapt=1.11.2=py36he774522_0
  - xarray=0.14.1=py_0
  - xlrd=1.2.0=py36_0
  - xlsxwriter=1.2.6=py_0
  - xlwings=0.16.0=py36_0
  - xlwt=1.3.0=py36h1a4751e_0
  - xz=5.2.4=h2fa13f4_4
  - yaml=0.1.7=hc54c509_2
  - zeromq=4.3.1=h33f27b4_3
  - zict=1.0.0=py_0
  - zipp=0.6.0=py_0
  - zlib=1.2.11=h62dcd97_3
  - zstd=1.3.7=h508b16e_0
  - pip:
    - absl-py==0.8.1
    - alpha-vantage==2.1.2
    - arctic==1.79.2
    - astor==0.8.0
    - boto3==1.10.30
    - botocore==1.13.30
    - cachetools==3.1.1
    - chart-studio==1.0.0
    - chartpy==0.1.4
    - colorlover==0.3.0
    - configparser==4.0.2
    - cssselect==1.1.0
    - cufflinks==0.17.0
    - dash==1.1.1
    - dash-core-components==1.1.1
    - dash-html-components==1.0.0
    - dash-renderer==1.0.0
    - dash-table==4.1.0
    - enum-compat==0.0.3
    - feedfinder2==0.0.4
    - feedparser==5.2.1
    - findatapy==0.1.6
    - finmarketpy==0.11.3
    - flask-compress==1.4.0
    - freetype-py==2.1.0.post1
    - fxcmpy==1.2.5
    - gast==0.2.2
    - gensim==3.8.1
    - google-auth==1.7.1
    - google-auth-oauthlib==0.4.1
    - google-pasta==0.1.8
    - grpcio==1.25.0
    - jieba3k==0.35.1
    - jmespath==0.9.4
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.0
    - lz4==2.2.1
    - markdown==3.1.1
    - mockextras==1.0.2
    - multiprocessing-on-dill==3.5.0a4
    - multitasking==0.0.9
    - newspaper3k==0.2.8
    - oauthlib==3.1.0
    - opt-einsum==3.1.0
    - pandas-datareader==0.8.1
    - pdfkit==0.6.1
    - pdfminer-six==20191110
    - plotly==4.2.1
    - plotly-express==0.4.1
    - prompt-toolkit==2.0.10
    - protobuf==3.11.1
    - pyarrow==0.15.1
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.7
    - pycryptodome==3.9.4
    - pymongo==3.9.0
    - python-dateutil==2.8.0
    - regex==2019.11.1
    - requests-file==1.4.3
    - requests-oauthlib==1.3.0
    - retrying==1.3.3
    - rsa==4.0
    - s3transfer==0.2.1
    - sacremoses==0.0.35
    - seasonal==0.3.1
    - sentencepiece==0.1.83
    - smart-open==1.9.0
    - socketio-client==0.7.2
    - tensorboard==2.0.2
    - tensorflow==2.0.0
    - tensorflow-estimator==2.0.1
    - termcolor==1.1.0
    - tinysegmenter==0.3
    - tldextract==2.2.2
    - transformers==2.2.0
    - twython==3.7.0
    - tzlocal==2.0.0
    - vadersentiment==3.2.1
    - vispy==0.6.3
    - websocket-client==0.56.0
    - yfinance==0.1.50

